### ISSUE TITLE
Robot cannot wear Skinsuit or be attached to Keychain

### ISSUE THREAD

**Issue by BranMuffinz** [The-Fireplace/Mechanical-Soldiers#29]
My glorious robotic army cannot share my glorious face, nor can I sneakily transport my ace-in-the-hole terminator as an item. If the mod could be updated to support these features, I would greatly appreciated it.

**Comment by The-Fireplace** [comment]
These are both intentional. Lore-wise, the skin suit doesn't fit well over
robots' joints. Also, I designed the robots to look different based on how
you build and stain them, I don't particularly want to hide that with a
skin suit. As for the keychain thing, they have crates already if you
really want to deploy them at the site of a battle. However, showing up and
instantly dropping in 36 terminators from out of nowhere doesn't really
sound like a fair fight, you know?
